// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: grpc/malcolms_service.proto

// gRPC service definition.

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_malcolms_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_malcolms_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_grpc_malcolms_service_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Boundaries describes the bounding box of an inversion problem.
// Infima are the lower bounds of the parameter space, while suprema are the higher bounds.
type Boundaries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dimension int64     `protobuf:"varint,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Infima    []float64 `protobuf:"fixed64,2,rep,packed,name=infima,proto3" json:"infima,omitempty"`
	Suprema   []float64 `protobuf:"fixed64,3,rep,packed,name=suprema,proto3" json:"suprema,omitempty"`
}

func (x *Boundaries) Reset() {
	*x = Boundaries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_malcolms_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boundaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boundaries) ProtoMessage() {}

func (x *Boundaries) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_malcolms_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boundaries.ProtoReflect.Descriptor instead.
func (*Boundaries) Descriptor() ([]byte, []int) {
	return file_grpc_malcolms_service_proto_rawDescGZIP(), []int{1}
}

func (x *Boundaries) GetDimension() int64 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *Boundaries) GetInfima() []float64 {
	if x != nil {
		return x.Infima
	}
	return nil
}

func (x *Boundaries) GetSuprema() []float64 {
	if x != nil {
		return x.Suprema
	}
	return nil
}

// WalkRequest describes a starting point with a requested number of samples.
// starting_point must be of correct dimension.
type WalkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid            string    `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	StartingPoint   []float64 `protobuf:"fixed64,1,rep,packed,name=starting_point,json=startingPoint,proto3" json:"starting_point,omitempty"`
	NumberOfSamples int64     `protobuf:"varint,2,opt,name=number_of_samples,json=numberOfSamples,proto3" json:"number_of_samples,omitempty"`
}

func (x *WalkRequest) Reset() {
	*x = WalkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_malcolms_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkRequest) ProtoMessage() {}

func (x *WalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_malcolms_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkRequest.ProtoReflect.Descriptor instead.
func (*WalkRequest) Descriptor() ([]byte, []int) {
	return file_grpc_malcolms_service_proto_rawDescGZIP(), []int{2}
}

func (x *WalkRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WalkRequest) GetStartingPoint() []float64 {
	if x != nil {
		return x.StartingPoint
	}
	return nil
}

func (x *WalkRequest) GetNumberOfSamples() int64 {
	if x != nil {
		return x.NumberOfSamples
	}
	return 0
}

// Samples represents a list of samples stored in a 1D array.
// It can be used to store 1 or more data points consecutively.
// Hence, the length of the array must be a multiple of the dimension.
type Samples struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Coordinates []float64 `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *Samples) Reset() {
	*x = Samples{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_malcolms_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Samples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Samples) ProtoMessage() {}

func (x *Samples) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_malcolms_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Samples.ProtoReflect.Descriptor instead.
func (*Samples) Descriptor() ([]byte, []int) {
	return file_grpc_malcolms_service_proto_rawDescGZIP(), []int{3}
}

func (x *Samples) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Samples) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

// TrueSamples represents a list of samples in a 1D array with posterior values.
type TrueSamples struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid            string    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Coordinates     []float64 `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	PosteriorValues []float64 `protobuf:"fixed64,3,rep,packed,name=posterior_values,json=posteriorValues,proto3" json:"posterior_values,omitempty"`
}

func (x *TrueSamples) Reset() {
	*x = TrueSamples{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_malcolms_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrueSamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrueSamples) ProtoMessage() {}

func (x *TrueSamples) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_malcolms_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrueSamples.ProtoReflect.Descriptor instead.
func (*TrueSamples) Descriptor() ([]byte, []int) {
	return file_grpc_malcolms_service_proto_rawDescGZIP(), []int{4}
}

func (x *TrueSamples) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *TrueSamples) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *TrueSamples) GetPosteriorValues() []float64 {
	if x != nil {
		return x.PosteriorValues
	}
	return nil
}

var File_grpc_malcolms_service_proto protoreflect.FileDescriptor

var file_grpc_malcolms_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6d, 0x61, 0x6c, 0x63, 0x6f, 0x6c, 0x6d, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x1a, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22,
	0x5c, 0x0a, 0x0a, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x6e, 0x66, 0x69, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x69, 0x6e, 0x66,
	0x69, 0x6d, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x70, 0x72, 0x65, 0x6d, 0x61, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x73, 0x75, 0x70, 0x72, 0x65, 0x6d, 0x61, 0x22, 0x74, 0x0a,
	0x0b, 0x57, 0x61, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x07, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x22, 0x6e, 0x0a, 0x0b, 0x54, 0x72, 0x75, 0x65, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x63, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x6f, 0x73,
	0x74, 0x65, 0x72, 0x69, 0x6f, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x0f, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x69, 0x6f, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x32, 0xa4, 0x01, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73,
	0x65, 0x72, 0x12, 0x2f, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x72, 0x75, 0x65, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x54, 0x72, 0x75, 0x65, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x1a, 0x0a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x22, 0x00, 0x28, 0x01, 0x12, 0x2c, 0x0a,
	0x04, 0x57, 0x61, 0x6c, 0x6b, 0x12, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x61, 0x6c,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x2d, 0x6e, 0x6f, 0x72, 0x64,
	0x6d, 0x61, 0x6e, 0x6e, 0x2f, 0x6d, 0x61, 0x6c, 0x63, 0x6f, 0x6c, 0x6d, 0x2d, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpc_malcolms_service_proto_rawDescOnce sync.Once
	file_grpc_malcolms_service_proto_rawDescData = file_grpc_malcolms_service_proto_rawDesc
)

func file_grpc_malcolms_service_proto_rawDescGZIP() []byte {
	file_grpc_malcolms_service_proto_rawDescOnce.Do(func() {
		file_grpc_malcolms_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_malcolms_service_proto_rawDescData)
	})
	return file_grpc_malcolms_service_proto_rawDescData
}

var file_grpc_malcolms_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_malcolms_service_proto_goTypes = []interface{}{
	(*UUID)(nil),        // 0: grpc.UUID
	(*Boundaries)(nil),  // 1: grpc.Boundaries
	(*WalkRequest)(nil), // 2: grpc.WalkRequest
	(*Samples)(nil),     // 3: grpc.Samples
	(*TrueSamples)(nil), // 4: grpc.TrueSamples
}
var file_grpc_malcolms_service_proto_depIdxs = []int32{
	1, // 0: grpc.Appraiser.PutBoundaries:input_type -> grpc.Boundaries
	4, // 1: grpc.Appraiser.RegisterTrueSamples:input_type -> grpc.TrueSamples
	2, // 2: grpc.Appraiser.Walk:input_type -> grpc.WalkRequest
	0, // 3: grpc.Appraiser.PutBoundaries:output_type -> grpc.UUID
	0, // 4: grpc.Appraiser.RegisterTrueSamples:output_type -> grpc.UUID
	3, // 5: grpc.Appraiser.Walk:output_type -> grpc.Samples
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_malcolms_service_proto_init() }
func file_grpc_malcolms_service_proto_init() {
	if File_grpc_malcolms_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_malcolms_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_malcolms_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boundaries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_malcolms_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_malcolms_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Samples); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_malcolms_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrueSamples); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_malcolms_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_malcolms_service_proto_goTypes,
		DependencyIndexes: file_grpc_malcolms_service_proto_depIdxs,
		MessageInfos:      file_grpc_malcolms_service_proto_msgTypes,
	}.Build()
	File_grpc_malcolms_service_proto = out.File
	file_grpc_malcolms_service_proto_rawDesc = nil
	file_grpc_malcolms_service_proto_goTypes = nil
	file_grpc_malcolms_service_proto_depIdxs = nil
}
